# Generated by Django 4.0.3 on 2022-09-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answeranggota_score_question_level_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('EASY', 'Multiple Choice/ Sejenis'), ('MEDI', 'Esai'), ('HARD', 'AKM')], default='EASY', max_length=4),
            preserve_default=False,
        ),
    ]
