# Generated by Django 4.0.3 on 2022-09-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeranggota',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('EASY', 'EASY'), ('MEDI', 'MEDIUM'), ('HARD', 'HARD'), ('SEMI', 'SEMIFINAL')], max_length=4),
        ),
        migrations.AlterField(
            model_name='question',
            name='tipe',
            field=models.CharField(choices=[('PG', 'Multiple Choice/ Sejenis'), ('ES', 'Esai'), ('AKM', 'AKM'), ('SB', 'Spelling Bee')], max_length=3),
        ),
    ]
