# Generated by Django 4.0.3 on 2022-09-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_answeranggota_score_alter_question_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
