# Generated by Django 4.0.3 on 2022-09-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lomba',
            field=models.CharField(choices=[('SB', 'SPELLING BEE'), ('EQ', 'ENGLISH QUIZ')], default='SB', max_length=2),
            preserve_default=False,
        ),
    ]
