# Generated by Django 4.0.3 on 2022-09-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_team_lomba'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lolos',
            field=models.BooleanField(default=False),
        ),
    ]
